name: 🐛 Bug Report
description: Create a report to help us improve VulnScanner
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tested with the latest version of VulnScanner
          required: true
        - label: I have run the test suite (`python tests/test_run_all.py`) to verify my installation
          required: false

  - type: input
    id: version
    attributes:
      label: VulnScanner Version
      description: What version of VulnScanner are you running?
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide details about your environment
      placeholder: |
        - OS: (e.g., Windows 11, Ubuntu 22.04, macOS 13)
        - Python Version: (e.g., 3.11.5)
        - Installation Method: (e.g., pip, from source)
        - Virtual Environment: (e.g., venv, conda)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Set environment variable '...'
        3. Execute '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      render: shell
      placeholder: |
        Paste your error logs here. Use --debug flag for verbose output:
        vulnscanner nvd-sync --debug

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Screenshots (if applicable)
        - Related issues or PRs
        - Workarounds you've tried
        - Any other relevant information
